rmdir Upperbay\Agent\BaseCell\bin /s /q
rmdir Upperbay\Agent\BaseCell\obj /s /q
rmdir Upperbay\Agent\Colony\bin /s /q
rmdir Upperbay\Agent\Colony\obj /s /q
rmdir Upperbay\Agent\ColonyMatrix\bin /s /q
rmdir Upperbay\Agent\ColonyMatrix\obj /s /q
rmdir Upperbay\Agent\ConfigurationSettings\bin /s /q
rmdir Upperbay\Agent\ConfigurationSettings\obj /s /q
rmdir Upperbay\Agent\Interfaces\bin /s /q
rmdir Upperbay\Agent\Interfaces\obj /s /q
rmdir Upperbay\AgentObjects\ClusterAgent\bin /s /q
rmdir Upperbay\AgentObjects\ClusterAgent\obj /s /q
rmdir Upperbay\Assistant\Cache\bin /s /q
rmdir Upperbay\Assistant\Cache\obj /s /q
rmdir Upperbay\Assistant\CloudMqttPublisher\bin /s /q
rmdir Upperbay\Assistant\CloudMqttPublisher\obj /s /q
rmdir Upperbay\Assistant\EtherReadTestAccessor\bin /s /q
rmdir Upperbay\Assistant\EtherReadTestAccessor\obj /s /q
rmdir Upperbay\Assistant\EtherWriteTestAccessor\bin /s /q
rmdir Upperbay\Assistant\EtherWriteTestAccessor\obj /s /q
rmdir Upperbay\Assistant\EventReactor\bin /s /q
rmdir Upperbay\Assistant\EventReactor\obj /s /q
rmdir Upperbay\Assistant\GameEventReactor\bin /s /q
rmdir Upperbay\Assistant\GameEventReactor\obj /s /q
rmdir Upperbay\Assistant\ManualInput\bin /s /q
rmdir Upperbay\Assistant\ManualInput\obj /s /q
rmdir Upperbay\Assistant\MqttPublisher\bin /s /q
rmdir Upperbay\Assistant\MqttPublisher\obj /s /q
rmdir Upperbay\Assistant\Simulator\bin /s /q
rmdir Upperbay\Assistant\Simulator\obj /s /q
rmdir Upperbay\Assistant\ThingSpeakReadAccessor\bin /s /q
rmdir Upperbay\Assistant\ThingSpeakReadAccessor\obj /s /q
rmdir Upperbay\Assistant\ThingSpeakWriteAccessor\bin /s /q
rmdir Upperbay\Assistant\ThingSpeakWriteAccessor\obj /s /q
rmdir Upperbay\Assistant\TimeKeeper\bin /s /q
rmdir Upperbay\Assistant\TimeKeeper\obj /s /q
rmdir Upperbay\Assistant\VariableProcessing\bin /s /q
rmdir Upperbay\Assistant\VariableProcessing\obj /s /q
rmdir Upperbay\Core\Library\bin /s /q
rmdir Upperbay\Core\Library\obj /s /q
rmdir Upperbay\Worker\Ears\bin /s /q
rmdir Upperbay\Worker\Ears\obj /s /q
rmdir Upperbay\Worker\Ethereum\bin /s /q
rmdir Upperbay\Worker\Ethereum\obj /s /q
rmdir Upperbay\Worker\Events\bin /s /q
rmdir Upperbay\Worker\Events\obj /s /q
rmdir Upperbay\Worker\Hasher\bin /s /q
rmdir Upperbay\Worker\Hasher\obj /s /q
rmdir Upperbay\Worker\JSON\bin /s /q
rmdir Upperbay\Worker\JSON\obj /s /q
rmdir Upperbay\Worker\MQTT\bin /s /q
rmdir Upperbay\Worker\MQTT\obj /s /q
rmdir Upperbay\Worker\PostOffice\bin /s /q
rmdir Upperbay\Worker\PostOffice\obj /s /q
rmdir Upperbay\Worker\ThingSpeak\bin /s /q
rmdir Upperbay\Worker\ThingSpeak\obj /s /q
rmdir Upperbay\Worker\Timers\bin /s /q
rmdir Upperbay\Worker\Timers\obj /s /q
rmdir Upperbay\Worker\Voice\bin /s /q
rmdir Upperbay\Worker\Voice\obj /s /q
